### ISSUE TITLE
Compare individuals

### ISSUE THREAD

**Issue by Vayel** [MaxHalford/ethik#101]
For two individuals:

- [ ] Plot the two PDFs of the features, plus the PDF of the original dataset
- [ ] Plot the two PDFs of the output, plus the PDF of the original output
- [ ] The difference in influence between the individuals for each feature

**Comment by Vayel** [comment]
@MaxHalford available this week to talk about that?

**Comment by MaxHalford** [comment]
Yep I'll come by Wednesday afternoon.
