### ISSUE TITLE
Commit tags are not detected by Travis

### ISSUE THREAD

**Issue by Vayel** [MaxHalford/ethik#89]
https://travis-ci.org/MaxHalford/ethik/builds/592547774?utm_source=github_status&utm_medium=notification

but the tag is here: https://github.com/MaxHalford/ethik/tags

**Comment by Vayel** [comment]
They use a different syntax than `if: tag IS present` in the docs: https://docs.travis-ci.com/user/deployment/pypi/#deploying-tags

**Comment by MaxHalford** [comment]
Yeah I remember seeing both. I'll give it a try by deleting the tag on GitHub and retrying. Just give me a minute.
