### ISSUE TITLE
Compute local bias

### ISSUE THREAD

**Issue by Vayel** [MaxHalford/ethik#90]
Add a method `explain_local_bias(X_test, y_pred, around, n_neighbours)` and `explain_local_performance()`

**Make sure to normalize features** before computing the distances.

**Comment by Vayel** [comment]
It raises an issue with memoization. The second call will return the cached explanation:

```python
explainer.explain_local_bias(
    X_test=X_test['education-num'],
    y_pred=y_pred,
    point=X_test['education-num'].iloc[0],
)
```

```python
explainer.explain_local_bias(
    X_test=X_test['education-num'],
    y_pred=y_pred,
    point=X_test['education-num'].iloc[1],  # Another point
)
```

**Comment by Vayel** [comment]
To compute the "local" bias, we can just:

1. Take a point
2. Compute the influence of each feature at this point (by stressing the dataset so that its mean is equal to the point's value)
3. Take the difference with the influence at the original mean
4. Plot that on a radar plot with a green bar if the delta is positive, a red bar otherwise

**Comment by Vayel** [comment]
@MaxHalford would you create another method `explain_individual_influence()` (or something else) or would you add a parameter (e.g. `individual`) to `explain_influence()`?

**Comment by MaxHalford** [comment]
Again, I'm not sure... SHAP uses a single method, but then again they don't have to pass the entire dataset. I think I prefer having a parameter called `individual` though. In England we say that's it 6 and two 3s, meaning that I don't think it matters too much in the end.
