### ISSUE TITLE
Use radar plots for ranking

### ISSUE THREAD

**Issue by Vayel** [MaxHalford/ethik#98]

**Comment by Vayel** [comment]
Actually, I find the bars clearer. What do you think @MaxHalford?

![image](https://user-images.githubusercontent.com/6124369/66818821-2dfbd380-ef3e-11e9-87e4-356a2189e627.png)

![image](https://user-images.githubusercontent.com/6124369/66818837-348a4b00-ef3e-11e9-80ec-b17c864934f2.png)

**Comment by MaxHalford** [comment]
I agree with you! As for the individual explanations, we could draw red bars towards the left for negative contributions, and green bars towards the right for positive contributions. In any case, it's good to try out different things.

**Comment by Vayel** [comment]
I agree for the individual explanations, but for this global ranking, there's no negative contribution.

**Comment by MaxHalford** [comment]
Maybe the bar chart would look prettier if the bar were less thick?

**Comment by Vayel** [comment]
![image](https://user-images.githubusercontent.com/6124369/66827508-23960580-ef4f-11e9-85bf-724771fc9568.png)
